### ISSUE TITLE
Problems displaying on Paquet

### ISSUE THREAD

**Issue by m4rocks** [adelpro/Quranipfs#8]
Due to some legal issues, I can't store app icons and screenshots anymore without the developer's specific consent. I am still working on that. Until then, I am displaying the icons and other resources directly to the user.

Unfortunately your app has some cross-origin restrictions and the icon cannot be displayed anywhere else. Could you please fix that and get back to me, so I can put QuranIPFS back on Paquet?

**Comment by adelpro** [comment]
Thanks for your interest in QuranIPFS, yes it will be a pleaser for us to be on Paquet.shop.
I opened a new issue in the Paquet repository on GitHub, as mentionned in the readme page

**Comment by m4rocks** [comment]
Hi @adelpro! Sorry, I think you misunderstood my issue. Your app has some cross-origin restrictions and Paquet cannot fetch your app's resources.

Your app is already on Paquet, but has been disabled due to this issue. See notangelmario/paquet#7.

**Comment by adelpro** [comment]
Can you be more specific?!
What files exactly cause this issue, and how Paquet is requesting these files!?
Thanks @notangelmario

**Comment by m4rocks** [comment]
Hello! For some reason, it seems the issue has been fixed, but there is still an issue with the `og:image`. It is way too small and it doesn't display properly. The optimal size would be 1024x600.

**Comment by adelpro** [comment]
Thanks @notangelmario for reporting this issue 
I will fix that by providing a bigger image (1024) for the `og:image`
meta tag

**Comment by adelpro** [comment]
Thanks @notangelmario for reporting this issue 
I will fix that by providing a bigger image (1024) for the og:image meta tag
